const fs = require('fs');
const path = require('path');

// Load .env manually without requiring dotenv
const envPath = path.resolve(__dirname, '../.env');
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const [key, ...rest] = trimmed.split('=');
    if (key && rest.length) {
      process.env[key.trim()] = rest.join('=').trim();
    }
  }
}

const content = `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: false,
  financeTrackerAPI: '${process.env.API_URL || 'http://localhost:5197'}',
};
`;

fs.writeFileSync(path.resolve(__dirname, '../src/environments/environment.ts'), content);
console.log('environment.ts generated from .env');
