// <auto-generated />
using System;
using Finance.Tracker.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finance.Tracker.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260408000000_AddRolesAndSiteSettings")]
    partial class AddRolesAndSiteSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finance.Tracker.Entities.Authentication.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").IsRequired().HasColumnType("text");
                    b.Property<DateTime?>("LastSeenAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                    b.Property<string>("Role").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("users", "authentications");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Finance.BudgetConfig", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<decimal>("Budget").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("budgetConfig", "finance");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Finance.CategoryLimit", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("CategoryId").HasColumnType("uuid");
                    b.Property<decimal>("Limit").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("CategoryId");
                    b.HasIndex("UserId", "CategoryId").IsUnique();
                    b.ToTable("categoryLimit", "finance");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Finance.Transaction", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<decimal>("Amount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<Guid>("CategoryId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("Date").HasColumnType("timestamp with time zone");
                    b.Property<string>("Desc").IsRequired().HasColumnType("text");
                    b.Property<string>("Type").IsRequired().HasColumnType("text");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("CategoryId");
                    b.HasIndex("UserId");
                    b.ToTable("transactions", "finance");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Parameters.Category", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Color").IsRequired().HasColumnType("text");
                    b.Property<string>("Icon").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsDefault").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<string>("Type").IsRequired().HasColumnType("text");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("categories", "parameters");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Settings.SiteSettings", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Feature1Desc").IsRequired().HasColumnType("text");
                    b.Property<string>("Feature1Title").IsRequired().HasColumnType("text");
                    b.Property<string>("Feature2Desc").IsRequired().HasColumnType("text");
                    b.Property<string>("Feature2Title").IsRequired().HasColumnType("text");
                    b.Property<string>("Feature3Desc").IsRequired().HasColumnType("text");
                    b.Property<string>("Feature3Title").IsRequired().HasColumnType("text");
                    b.Property<string>("LoginSubtitle").IsRequired().HasColumnType("text");
                    b.Property<string>("SiteName").IsRequired().HasColumnType("text");
                    b.Property<string>("Slogan").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("siteSettings", "settings");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Finance.BudgetConfig", b =>
                {
                    b.HasOne("Finance.Tracker.Entities.Authentication.User", "User")
                        .WithOne("BudgetConfig").HasForeignKey("Finance.Tracker.Entities.Finance.BudgetConfig", "UserId")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Finance.CategoryLimit", b =>
                {
                    b.HasOne("Finance.Tracker.Entities.Parameters.Category", "Category")
                        .WithMany("Limits").HasForeignKey("CategoryId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("Finance.Tracker.Entities.Authentication.User", "User")
                        .WithMany("CategoryLimits").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Category");
                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Finance.Transaction", b =>
                {
                    b.HasOne("Finance.Tracker.Entities.Parameters.Category", "Category")
                        .WithMany("Transactions").HasForeignKey("CategoryId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("Finance.Tracker.Entities.Authentication.User", "User")
                        .WithMany("Transactions").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Category");
                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Parameters.Category", b =>
                {
                    b.HasOne("Finance.Tracker.Entities.Authentication.User", "User")
                        .WithMany("Categories").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Authentication.User", b =>
                {
                    b.Navigation("BudgetConfig");
                    b.Navigation("Categories");
                    b.Navigation("CategoryLimits");
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Finance.Tracker.Entities.Parameters.Category", b =>
                {
                    b.Navigation("Limits");
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
